#! /bin/bash
. $HOME/thilenius/core/shell/base

rm -rf /root/thilenius/scorch/aws/packages

INFO 'Packaging Sentinel'
pushd /root/thilenius/cloud/sentinel/server
build --clean --release --package
popd
mkdir -p /root/thilenius/scorch/aws/packages/sentinel_package/
cp -r /root/thilenius_bin/cloud/sentinel/server/server_package/* \
    /root/thilenius/scorch/aws/packages/sentinel_package/

INFO 'Packaging Crucible'
pushd /root/thilenius/scorch/cloud/crucible/server
build --clean --release --package
popd
mkdir -p /root/thilenius/scorch/aws/packages/crucible_package/
cp -r /root/thilenius_bin/scorch/cloud/crucible/server/server_package/* \
    /root/thilenius/scorch/aws/packages/crucible_package/

INFO 'Packaging Billet'
pushd /root/thilenius/scorch/cloud/billet/server
build --clean --release --package
popd
mkdir -p /root/thilenius/scorch/aws/packages/billet_package/
cp -r /root/thilenius_bin/scorch/cloud/billet/server/server_package/* \
    /root/thilenius/scorch/aws/packages/billet_package/
