#!/bin/bash
. $HOME/thilenius/core/shell/base

INFO 'Buidling Thrift in Release mode'
pushd /root/thilenius/third_party/thrift
build --release || EROR 'Failed to build Thrift'
popd

INFO 'Building MongoDB in Release mode'
pushd /root/thilenius/third_party/mongo
build --release || EROR 'Failed to build MongoDB'
popd

INFO 'Updating libs'
sudo ldconfig

INFO 'Bootstrap done.'
