#!/bin/bash
. $HOME/thilenius/core/shell/base

INFO 'Compiling service files'
build_services --gen node\
    --out $HOME/thilenius/cloud/services/authentication/gen_files\
    $HOME/thilenius/cloud/services_def/authentication.thrift ||\
    EROR 'Failed to build authentication service files'

INFO 'Killing any old Docker Containers'
docker kill authentication_dev 2> /dev/null
docker rm authentication_dev 2> /dev/null

INFO 'Building Docker image'
docker build -t athilenius/authentication:dev\
    $HOME/thilenius/cloud/services/authentication ||\
    EROR 'Failed to build Dockerfile'

PORT=$(gcounter -k next_port)
SERVICE_ID=$(gcounter -k cloud_services_authentication_next_id)
INFO "Starting Docker container on port $PORT with id $SERVICE_ID"
CONTAINER_ID=$(docker run -d -p $PORT:80 --name authentication_dev\
    -e DOCKER_PORT=$PORT -e SERVICE_ID=$SERVICE_ID --env-file=/etc/environment\
    athilenius/authentication:dev)

INFO 'Cleaning up gen_files'
rm -rf $HOME/thilenius/cloud/services/authentication/gen_files

INFO "Started in container [$CONTAINER_ID]. Waiting a few seconds for logs"
sleep 4
docker logs $CONTAINER_ID
