#!/bin/bash
. $HOME/thilenius/core/shell/base

INFO 'Running CMAKE'
cmake -H. -B/root/thilenius_bin/scorch/anvil || EROR 'CMake command failed.'

cd /root/thilenius_bin/scorch/anvil

INFO 'Running GNU Make'
make || EROR 'MAKE command failed.'
