#! /bin/bash
source $HOME/thilenius/core/shell/log.sh

#===  DEV HELP  ================================================================
function __dev_print_usage {
  INFO 'dev'
  INFO 'Usage: dev [command] --args';
  INFO 'Commands:'
  INFO '  docker   - docker commands'
  WARN "[dev $1] is not a valid dev command"
}

#===  DOCKER  ==================================================================
function __dev_docker {
  if [ "$2" == "run" ]; then
    docker run --privileged -it -v $HOME/thilenius:/root/thilenius\
        -v /var/lib/docker:/var/lib/docker athilenius/dev_env #CMD: wrapdocker
  elif [ "$2" == "clean" ]; then
    INFO 'Removing untagged docker images'
    docker rmi $(docker images | grep "^<none>" | awk "{print $3}")
    INFO 'Removing all docker containers'
    docker rm $(docker ps -a -q)
  else
    INFO 'dev DOCKER'
    INFO 'Usage: dev docker [command]';
    INFO 'Commands:'
    INFO '  run    - Starts a new athilenius/dev container'
    INFO '  clean  - Cleans untagged images and all containers'
    WARN "[dev docker $1] is not a valid dev command"
  fi
}

#===  RUN  =====================================================================
if [ "$1" == "help" ]; then
  __dev_print_usage
elif [ "$1" == "docker" ]; then
  __dev_docker $@
else
  __dev_print_usage
fi
