#!/bin/bash
. $HOME/thilenius/core/shell/base

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

mkdir --parent /root/thilenius/scorch/client/gen-files

INFO 'Compiling lb Services'
lb-ng /root/thilenius/scorch/server/server.js \
    /root/thilenius/scorch/client/gen-files/lb_services.js || \
    EROR 'Failed to build lb service files'

TIMESTAMP=$(date +%y%m%d.%H.%M%S)

function GlobJsToIndex {
  find $1 -name *.js | while read line; do \
    echo "<script src=\"$line\"></script>" >> index.html; \
  done
}

function GlobCssToIndex {
  find $1 -name *.css | while read line; do \
    echo "<link rel=\"stylesheet\" href=\"$line\" />" >> index.html; \
  done
}

INFO 'Createing a development index.html file'
pushd /root/thilenius/scorch/client
rm -rf /root/thilenius/scorch/client/index.html
cat << EOM >> index.html
<!doctype html>
<html ng-app="app" ng-controller="loginController"
      class="{{\$root.htmlClass ? \$root.htmlClass : 'default-body'}}">
<head><title ng-bind="\$root.title || 'Scorch'"></title>
<link rel="shortcut icon" href="assets/flame-512.png" />
<link href="vendor/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
<link href="vendor/angular-xeditable/dist/css/xeditable.css" rel="stylesheet">
<link href="vendor/hover/css/hover-min.css" rel="stylesheet">
<link href="vendor/angular-material/angular-material.min.css" rel="stylesheet">
<script src="vendor/jquery/dist/jquery.js"></script>
<script src="vendor/bootstrap/dist/js/bootstrap.js"></script>
<script src="vendor/angular/angular.js"></script>
<script src="vendor/angular-animate/angular-animate.min.js"></script>
<script src="vendor/angular-aria/angular-aria.min.js"></script>
<script src="vendor/angular-messages/angular-messages.min.js"></script>
<script src="vendor/angular-resource/angular-resource.js"></script>
<script src="vendor/angular-ui-router/release/angular-ui-router.js"></script>
<script src="vendor/angular-cookies/angular-cookies.js"></script>
<script src="vendor/angular-xeditable/dist/js/xeditable.js"></script>
<script src="vendor/angular-bootstrap-contextmenu/contextMenu.js"></script>
<script src="vendor/angular-drag-and-drop-lists/angular-drag-and-drop-lists.min.js"></script>
<script src="vendor/angular-material/angular-material.min.js"></script>
<script src="vendor/underscore/underscore-min.js"></script>
<script src="vendor/ace-min-noconflict/ace.js"></script>
<script src="vendor/ace-min-noconflict/ext-language_tools.js"></script>
EOM
echo "<script>var FORGE_VERSION=\"${TIMESTAMP}\";</script>" >> index.html

# Bower
pushd /root/thilenius/scorch
bower --allow-root install \
  ace-min-noconflict \
  angular \
  angular-animate \
  angular-aria \
  angular-bootstrap-contextmenu \
  angular-cookies \
  angular-drag-and-drop-lists \
  angular-material \
  angular-messages \
  angular-resource \
  angular-ui-router \
  angular-xeditable \
  bootstrap \
  hover \
  underscore
popd

GlobCssToIndex libs_precomp
GlobJsToIndex libs_precomp

GlobCssToIndex libs
GlobJsToIndex libs

GlobCssToIndex assets
GlobJsToIndex assets

GlobCssToIndex gen-files
GlobJsToIndex gen-files

GlobCssToIndex app
GlobJsToIndex app

cat << EOM >> index.html
</head>
<body class="{{\$root.bodyClass ? \$root.bodyClass : 'default-body'}}">
<div ui-view></div>
</body></html>
EOM
popd

