/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thilenius.blaze.proto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-20")
public class BlazeResponseWrapper implements org.apache.thrift.TBase<BlazeResponseWrapper, BlazeResponseWrapper._Fields>, java.io.Serializable, Cloneable, Comparable<BlazeResponseWrapper> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BlazeResponseWrapper");

  private static final org.apache.thrift.protocol.TField IS_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("is_exception", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField JSON_FIELD_DESC = new org.apache.thrift.protocol.TField("json", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BlazeResponseWrapperStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BlazeResponseWrapperTupleSchemeFactory());
  }

  public boolean is_exception; // required
  public String json; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IS_EXCEPTION((short)1, "is_exception"),
    JSON((short)2, "json");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IS_EXCEPTION
          return IS_EXCEPTION;
        case 2: // JSON
          return JSON;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IS_EXCEPTION_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IS_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("is_exception", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.JSON, new org.apache.thrift.meta_data.FieldMetaData("json", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BlazeResponseWrapper.class, metaDataMap);
  }

  public BlazeResponseWrapper() {
  }

  public BlazeResponseWrapper(
    boolean is_exception,
    String json)
  {
    this();
    this.is_exception = is_exception;
    setIs_exceptionIsSet(true);
    this.json = json;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BlazeResponseWrapper(BlazeResponseWrapper other) {
    __isset_bitfield = other.__isset_bitfield;
    this.is_exception = other.is_exception;
    if (other.isSetJson()) {
      this.json = other.json;
    }
  }

  public BlazeResponseWrapper deepCopy() {
    return new BlazeResponseWrapper(this);
  }

  @Override
  public void clear() {
    setIs_exceptionIsSet(false);
    this.is_exception = false;
    this.json = null;
  }

  public boolean isIs_exception() {
    return this.is_exception;
  }

  public BlazeResponseWrapper setIs_exception(boolean is_exception) {
    this.is_exception = is_exception;
    setIs_exceptionIsSet(true);
    return this;
  }

  public void unsetIs_exception() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IS_EXCEPTION_ISSET_ID);
  }

  /** Returns true if field is_exception is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_exception() {
    return EncodingUtils.testBit(__isset_bitfield, __IS_EXCEPTION_ISSET_ID);
  }

  public void setIs_exceptionIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IS_EXCEPTION_ISSET_ID, value);
  }

  public String getJson() {
    return this.json;
  }

  public BlazeResponseWrapper setJson(String json) {
    this.json = json;
    return this;
  }

  public void unsetJson() {
    this.json = null;
  }

  /** Returns true if field json is set (has been assigned a value) and false otherwise */
  public boolean isSetJson() {
    return this.json != null;
  }

  public void setJsonIsSet(boolean value) {
    if (!value) {
      this.json = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IS_EXCEPTION:
      if (value == null) {
        unsetIs_exception();
      } else {
        setIs_exception((Boolean)value);
      }
      break;

    case JSON:
      if (value == null) {
        unsetJson();
      } else {
        setJson((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IS_EXCEPTION:
      return Boolean.valueOf(isIs_exception());

    case JSON:
      return getJson();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IS_EXCEPTION:
      return isSetIs_exception();
    case JSON:
      return isSetJson();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BlazeResponseWrapper)
      return this.equals((BlazeResponseWrapper)that);
    return false;
  }

  public boolean equals(BlazeResponseWrapper that) {
    if (that == null)
      return false;

    boolean this_present_is_exception = true;
    boolean that_present_is_exception = true;
    if (this_present_is_exception || that_present_is_exception) {
      if (!(this_present_is_exception && that_present_is_exception))
        return false;
      if (this.is_exception != that.is_exception)
        return false;
    }

    boolean this_present_json = true && this.isSetJson();
    boolean that_present_json = true && that.isSetJson();
    if (this_present_json || that_present_json) {
      if (!(this_present_json && that_present_json))
        return false;
      if (!this.json.equals(that.json))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_is_exception = true;
    list.add(present_is_exception);
    if (present_is_exception)
      list.add(is_exception);

    boolean present_json = true && (isSetJson());
    list.add(present_json);
    if (present_json)
      list.add(json);

    return list.hashCode();
  }

  @Override
  public int compareTo(BlazeResponseWrapper other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIs_exception()).compareTo(other.isSetIs_exception());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_exception()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_exception, other.is_exception);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetJson()).compareTo(other.isSetJson());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJson()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.json, other.json);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BlazeResponseWrapper(");
    boolean first = true;

    sb.append("is_exception:");
    sb.append(this.is_exception);
    first = false;
    if (!first) sb.append(", ");
    sb.append("json:");
    if (this.json == null) {
      sb.append("null");
    } else {
      sb.append(this.json);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BlazeResponseWrapperStandardSchemeFactory implements SchemeFactory {
    public BlazeResponseWrapperStandardScheme getScheme() {
      return new BlazeResponseWrapperStandardScheme();
    }
  }

  private static class BlazeResponseWrapperStandardScheme extends StandardScheme<BlazeResponseWrapper> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BlazeResponseWrapper struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IS_EXCEPTION
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_exception = iprot.readBool();
              struct.setIs_exceptionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // JSON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.json = iprot.readString();
              struct.setJsonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BlazeResponseWrapper struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(IS_EXCEPTION_FIELD_DESC);
      oprot.writeBool(struct.is_exception);
      oprot.writeFieldEnd();
      if (struct.json != null) {
        oprot.writeFieldBegin(JSON_FIELD_DESC);
        oprot.writeString(struct.json);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BlazeResponseWrapperTupleSchemeFactory implements SchemeFactory {
    public BlazeResponseWrapperTupleScheme getScheme() {
      return new BlazeResponseWrapperTupleScheme();
    }
  }

  private static class BlazeResponseWrapperTupleScheme extends TupleScheme<BlazeResponseWrapper> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BlazeResponseWrapper struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIs_exception()) {
        optionals.set(0);
      }
      if (struct.isSetJson()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetIs_exception()) {
        oprot.writeBool(struct.is_exception);
      }
      if (struct.isSetJson()) {
        oprot.writeString(struct.json);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BlazeResponseWrapper struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.is_exception = iprot.readBool();
        struct.setIs_exceptionIsSet(true);
      }
      if (incoming.get(1)) {
        struct.json = iprot.readString();
        struct.setJsonIsSet(true);
      }
    }
  }

}

