/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thilenius.blaze.proto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-20")
public class BlazeRequestWrapper implements org.apache.thrift.TBase<BlazeRequestWrapper, BlazeRequestWrapper._Fields>, java.io.Serializable, Cloneable, Comparable<BlazeRequestWrapper> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BlazeRequestWrapper");

  private static final org.apache.thrift.protocol.TField USER_UUID_FIELD_DESC = new org.apache.thrift.protocol.TField("user_uuid", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField MINECRAFT_USERNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("minecraft_username", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField COMMAND_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("command_name", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField ARGS_JSON_FIELD_DESC = new org.apache.thrift.protocol.TField("args_json", org.apache.thrift.protocol.TType.LIST, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BlazeRequestWrapperStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BlazeRequestWrapperTupleSchemeFactory());
  }

  public String user_uuid; // required
  public String minecraft_username; // required
  public String command_name; // required
  public List<String> args_json; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_UUID((short)1, "user_uuid"),
    MINECRAFT_USERNAME((short)2, "minecraft_username"),
    COMMAND_NAME((short)3, "command_name"),
    ARGS_JSON((short)4, "args_json");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_UUID
          return USER_UUID;
        case 2: // MINECRAFT_USERNAME
          return MINECRAFT_USERNAME;
        case 3: // COMMAND_NAME
          return COMMAND_NAME;
        case 4: // ARGS_JSON
          return ARGS_JSON;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_UUID, new org.apache.thrift.meta_data.FieldMetaData("user_uuid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MINECRAFT_USERNAME, new org.apache.thrift.meta_data.FieldMetaData("minecraft_username", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COMMAND_NAME, new org.apache.thrift.meta_data.FieldMetaData("command_name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ARGS_JSON, new org.apache.thrift.meta_data.FieldMetaData("args_json", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BlazeRequestWrapper.class, metaDataMap);
  }

  public BlazeRequestWrapper() {
  }

  public BlazeRequestWrapper(
    String user_uuid,
    String minecraft_username,
    String command_name,
    List<String> args_json)
  {
    this();
    this.user_uuid = user_uuid;
    this.minecraft_username = minecraft_username;
    this.command_name = command_name;
    this.args_json = args_json;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BlazeRequestWrapper(BlazeRequestWrapper other) {
    if (other.isSetUser_uuid()) {
      this.user_uuid = other.user_uuid;
    }
    if (other.isSetMinecraft_username()) {
      this.minecraft_username = other.minecraft_username;
    }
    if (other.isSetCommand_name()) {
      this.command_name = other.command_name;
    }
    if (other.isSetArgs_json()) {
      List<String> __this__args_json = new ArrayList<String>(other.args_json);
      this.args_json = __this__args_json;
    }
  }

  public BlazeRequestWrapper deepCopy() {
    return new BlazeRequestWrapper(this);
  }

  @Override
  public void clear() {
    this.user_uuid = null;
    this.minecraft_username = null;
    this.command_name = null;
    this.args_json = null;
  }

  public String getUser_uuid() {
    return this.user_uuid;
  }

  public BlazeRequestWrapper setUser_uuid(String user_uuid) {
    this.user_uuid = user_uuid;
    return this;
  }

  public void unsetUser_uuid() {
    this.user_uuid = null;
  }

  /** Returns true if field user_uuid is set (has been assigned a value) and false otherwise */
  public boolean isSetUser_uuid() {
    return this.user_uuid != null;
  }

  public void setUser_uuidIsSet(boolean value) {
    if (!value) {
      this.user_uuid = null;
    }
  }

  public String getMinecraft_username() {
    return this.minecraft_username;
  }

  public BlazeRequestWrapper setMinecraft_username(String minecraft_username) {
    this.minecraft_username = minecraft_username;
    return this;
  }

  public void unsetMinecraft_username() {
    this.minecraft_username = null;
  }

  /** Returns true if field minecraft_username is set (has been assigned a value) and false otherwise */
  public boolean isSetMinecraft_username() {
    return this.minecraft_username != null;
  }

  public void setMinecraft_usernameIsSet(boolean value) {
    if (!value) {
      this.minecraft_username = null;
    }
  }

  public String getCommand_name() {
    return this.command_name;
  }

  public BlazeRequestWrapper setCommand_name(String command_name) {
    this.command_name = command_name;
    return this;
  }

  public void unsetCommand_name() {
    this.command_name = null;
  }

  /** Returns true if field command_name is set (has been assigned a value) and false otherwise */
  public boolean isSetCommand_name() {
    return this.command_name != null;
  }

  public void setCommand_nameIsSet(boolean value) {
    if (!value) {
      this.command_name = null;
    }
  }

  public int getArgs_jsonSize() {
    return (this.args_json == null) ? 0 : this.args_json.size();
  }

  public java.util.Iterator<String> getArgs_jsonIterator() {
    return (this.args_json == null) ? null : this.args_json.iterator();
  }

  public void addToArgs_json(String elem) {
    if (this.args_json == null) {
      this.args_json = new ArrayList<String>();
    }
    this.args_json.add(elem);
  }

  public List<String> getArgs_json() {
    return this.args_json;
  }

  public BlazeRequestWrapper setArgs_json(List<String> args_json) {
    this.args_json = args_json;
    return this;
  }

  public void unsetArgs_json() {
    this.args_json = null;
  }

  /** Returns true if field args_json is set (has been assigned a value) and false otherwise */
  public boolean isSetArgs_json() {
    return this.args_json != null;
  }

  public void setArgs_jsonIsSet(boolean value) {
    if (!value) {
      this.args_json = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_UUID:
      if (value == null) {
        unsetUser_uuid();
      } else {
        setUser_uuid((String)value);
      }
      break;

    case MINECRAFT_USERNAME:
      if (value == null) {
        unsetMinecraft_username();
      } else {
        setMinecraft_username((String)value);
      }
      break;

    case COMMAND_NAME:
      if (value == null) {
        unsetCommand_name();
      } else {
        setCommand_name((String)value);
      }
      break;

    case ARGS_JSON:
      if (value == null) {
        unsetArgs_json();
      } else {
        setArgs_json((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_UUID:
      return getUser_uuid();

    case MINECRAFT_USERNAME:
      return getMinecraft_username();

    case COMMAND_NAME:
      return getCommand_name();

    case ARGS_JSON:
      return getArgs_json();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_UUID:
      return isSetUser_uuid();
    case MINECRAFT_USERNAME:
      return isSetMinecraft_username();
    case COMMAND_NAME:
      return isSetCommand_name();
    case ARGS_JSON:
      return isSetArgs_json();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BlazeRequestWrapper)
      return this.equals((BlazeRequestWrapper)that);
    return false;
  }

  public boolean equals(BlazeRequestWrapper that) {
    if (that == null)
      return false;

    boolean this_present_user_uuid = true && this.isSetUser_uuid();
    boolean that_present_user_uuid = true && that.isSetUser_uuid();
    if (this_present_user_uuid || that_present_user_uuid) {
      if (!(this_present_user_uuid && that_present_user_uuid))
        return false;
      if (!this.user_uuid.equals(that.user_uuid))
        return false;
    }

    boolean this_present_minecraft_username = true && this.isSetMinecraft_username();
    boolean that_present_minecraft_username = true && that.isSetMinecraft_username();
    if (this_present_minecraft_username || that_present_minecraft_username) {
      if (!(this_present_minecraft_username && that_present_minecraft_username))
        return false;
      if (!this.minecraft_username.equals(that.minecraft_username))
        return false;
    }

    boolean this_present_command_name = true && this.isSetCommand_name();
    boolean that_present_command_name = true && that.isSetCommand_name();
    if (this_present_command_name || that_present_command_name) {
      if (!(this_present_command_name && that_present_command_name))
        return false;
      if (!this.command_name.equals(that.command_name))
        return false;
    }

    boolean this_present_args_json = true && this.isSetArgs_json();
    boolean that_present_args_json = true && that.isSetArgs_json();
    if (this_present_args_json || that_present_args_json) {
      if (!(this_present_args_json && that_present_args_json))
        return false;
      if (!this.args_json.equals(that.args_json))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_user_uuid = true && (isSetUser_uuid());
    list.add(present_user_uuid);
    if (present_user_uuid)
      list.add(user_uuid);

    boolean present_minecraft_username = true && (isSetMinecraft_username());
    list.add(present_minecraft_username);
    if (present_minecraft_username)
      list.add(minecraft_username);

    boolean present_command_name = true && (isSetCommand_name());
    list.add(present_command_name);
    if (present_command_name)
      list.add(command_name);

    boolean present_args_json = true && (isSetArgs_json());
    list.add(present_args_json);
    if (present_args_json)
      list.add(args_json);

    return list.hashCode();
  }

  @Override
  public int compareTo(BlazeRequestWrapper other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUser_uuid()).compareTo(other.isSetUser_uuid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUser_uuid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.user_uuid, other.user_uuid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMinecraft_username()).compareTo(other.isSetMinecraft_username());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinecraft_username()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.minecraft_username, other.minecraft_username);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCommand_name()).compareTo(other.isSetCommand_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommand_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.command_name, other.command_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetArgs_json()).compareTo(other.isSetArgs_json());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetArgs_json()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.args_json, other.args_json);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BlazeRequestWrapper(");
    boolean first = true;

    sb.append("user_uuid:");
    if (this.user_uuid == null) {
      sb.append("null");
    } else {
      sb.append(this.user_uuid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("minecraft_username:");
    if (this.minecraft_username == null) {
      sb.append("null");
    } else {
      sb.append(this.minecraft_username);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("command_name:");
    if (this.command_name == null) {
      sb.append("null");
    } else {
      sb.append(this.command_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("args_json:");
    if (this.args_json == null) {
      sb.append("null");
    } else {
      sb.append(this.args_json);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BlazeRequestWrapperStandardSchemeFactory implements SchemeFactory {
    public BlazeRequestWrapperStandardScheme getScheme() {
      return new BlazeRequestWrapperStandardScheme();
    }
  }

  private static class BlazeRequestWrapperStandardScheme extends StandardScheme<BlazeRequestWrapper> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BlazeRequestWrapper struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_UUID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.user_uuid = iprot.readString();
              struct.setUser_uuidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MINECRAFT_USERNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.minecraft_username = iprot.readString();
              struct.setMinecraft_usernameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // COMMAND_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.command_name = iprot.readString();
              struct.setCommand_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ARGS_JSON
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.args_json = new ArrayList<String>(_list0.size);
                String _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readString();
                  struct.args_json.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setArgs_jsonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BlazeRequestWrapper struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.user_uuid != null) {
        oprot.writeFieldBegin(USER_UUID_FIELD_DESC);
        oprot.writeString(struct.user_uuid);
        oprot.writeFieldEnd();
      }
      if (struct.minecraft_username != null) {
        oprot.writeFieldBegin(MINECRAFT_USERNAME_FIELD_DESC);
        oprot.writeString(struct.minecraft_username);
        oprot.writeFieldEnd();
      }
      if (struct.command_name != null) {
        oprot.writeFieldBegin(COMMAND_NAME_FIELD_DESC);
        oprot.writeString(struct.command_name);
        oprot.writeFieldEnd();
      }
      if (struct.args_json != null) {
        oprot.writeFieldBegin(ARGS_JSON_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.args_json.size()));
          for (String _iter3 : struct.args_json)
          {
            oprot.writeString(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BlazeRequestWrapperTupleSchemeFactory implements SchemeFactory {
    public BlazeRequestWrapperTupleScheme getScheme() {
      return new BlazeRequestWrapperTupleScheme();
    }
  }

  private static class BlazeRequestWrapperTupleScheme extends TupleScheme<BlazeRequestWrapper> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BlazeRequestWrapper struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetUser_uuid()) {
        optionals.set(0);
      }
      if (struct.isSetMinecraft_username()) {
        optionals.set(1);
      }
      if (struct.isSetCommand_name()) {
        optionals.set(2);
      }
      if (struct.isSetArgs_json()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetUser_uuid()) {
        oprot.writeString(struct.user_uuid);
      }
      if (struct.isSetMinecraft_username()) {
        oprot.writeString(struct.minecraft_username);
      }
      if (struct.isSetCommand_name()) {
        oprot.writeString(struct.command_name);
      }
      if (struct.isSetArgs_json()) {
        {
          oprot.writeI32(struct.args_json.size());
          for (String _iter4 : struct.args_json)
          {
            oprot.writeString(_iter4);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BlazeRequestWrapper struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.user_uuid = iprot.readString();
        struct.setUser_uuidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.minecraft_username = iprot.readString();
        struct.setMinecraft_usernameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.command_name = iprot.readString();
        struct.setCommand_nameIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.args_json = new ArrayList<String>(_list5.size);
          String _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = iprot.readString();
            struct.args_json.add(_elem6);
          }
        }
        struct.setArgs_jsonIsSet(true);
      }
    }
  }

}

