/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thilenius.blaze.proto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-20")
public class BlazeCommandProcessor {

  public interface Iface {

    public BlazeResponseWrapper Process(BlazeRequestWrapper blaze_request) throws OperationFailure, org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void Process(BlazeRequestWrapper blaze_request, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public BlazeResponseWrapper Process(BlazeRequestWrapper blaze_request) throws OperationFailure, org.apache.thrift.TException
    {
      send_Process(blaze_request);
      return recv_Process();
    }

    public void send_Process(BlazeRequestWrapper blaze_request) throws org.apache.thrift.TException
    {
      Process_args args = new Process_args();
      args.setBlaze_request(blaze_request);
      sendBase("Process", args);
    }

    public BlazeResponseWrapper recv_Process() throws OperationFailure, org.apache.thrift.TException
    {
      Process_result result = new Process_result();
      receiveBase(result, "Process");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.operation_failure != null) {
        throw result.operation_failure;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "Process failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void Process(BlazeRequestWrapper blaze_request, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      Process_call method_call = new Process_call(blaze_request, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class Process_call extends org.apache.thrift.async.TAsyncMethodCall {
      private BlazeRequestWrapper blaze_request;
      public Process_call(BlazeRequestWrapper blaze_request, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.blaze_request = blaze_request;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("Process", org.apache.thrift.protocol.TMessageType.CALL, 0));
        Process_args args = new Process_args();
        args.setBlaze_request(blaze_request);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public BlazeResponseWrapper getResult() throws OperationFailure, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_Process();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("Process", new Process());
      return processMap;
    }

    public static class Process<I extends Iface> extends org.apache.thrift.ProcessFunction<I, Process_args> {
      public Process() {
        super("Process");
      }

      public Process_args getEmptyArgsInstance() {
        return new Process_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public Process_result getResult(I iface, Process_args args) throws org.apache.thrift.TException {
        Process_result result = new Process_result();
        try {
          result.success = iface.Process(args.blaze_request);
        } catch (OperationFailure operation_failure) {
          result.operation_failure = operation_failure;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("Process", new Process());
      return processMap;
    }

    public static class Process<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, Process_args, BlazeResponseWrapper> {
      public Process() {
        super("Process");
      }

      public Process_args getEmptyArgsInstance() {
        return new Process_args();
      }

      public AsyncMethodCallback<BlazeResponseWrapper> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<BlazeResponseWrapper>() { 
          public void onComplete(BlazeResponseWrapper o) {
            Process_result result = new Process_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            Process_result result = new Process_result();
            if (e instanceof OperationFailure) {
                        result.operation_failure = (OperationFailure) e;
                        result.setOperation_failureIsSet(true);
                        msg = result;
            }
             else 
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, Process_args args, org.apache.thrift.async.AsyncMethodCallback<BlazeResponseWrapper> resultHandler) throws TException {
        iface.Process(args.blaze_request,resultHandler);
      }
    }

  }

  public static class Process_args implements org.apache.thrift.TBase<Process_args, Process_args._Fields>, java.io.Serializable, Cloneable, Comparable<Process_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Process_args");

    private static final org.apache.thrift.protocol.TField BLAZE_REQUEST_FIELD_DESC = new org.apache.thrift.protocol.TField("blaze_request", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new Process_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new Process_argsTupleSchemeFactory());
    }

    public BlazeRequestWrapper blaze_request; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      BLAZE_REQUEST((short)1, "blaze_request");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // BLAZE_REQUEST
            return BLAZE_REQUEST;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.BLAZE_REQUEST, new org.apache.thrift.meta_data.FieldMetaData("blaze_request", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BlazeRequestWrapper.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Process_args.class, metaDataMap);
    }

    public Process_args() {
    }

    public Process_args(
      BlazeRequestWrapper blaze_request)
    {
      this();
      this.blaze_request = blaze_request;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public Process_args(Process_args other) {
      if (other.isSetBlaze_request()) {
        this.blaze_request = new BlazeRequestWrapper(other.blaze_request);
      }
    }

    public Process_args deepCopy() {
      return new Process_args(this);
    }

    @Override
    public void clear() {
      this.blaze_request = null;
    }

    public BlazeRequestWrapper getBlaze_request() {
      return this.blaze_request;
    }

    public Process_args setBlaze_request(BlazeRequestWrapper blaze_request) {
      this.blaze_request = blaze_request;
      return this;
    }

    public void unsetBlaze_request() {
      this.blaze_request = null;
    }

    /** Returns true if field blaze_request is set (has been assigned a value) and false otherwise */
    public boolean isSetBlaze_request() {
      return this.blaze_request != null;
    }

    public void setBlaze_requestIsSet(boolean value) {
      if (!value) {
        this.blaze_request = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case BLAZE_REQUEST:
        if (value == null) {
          unsetBlaze_request();
        } else {
          setBlaze_request((BlazeRequestWrapper)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case BLAZE_REQUEST:
        return getBlaze_request();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case BLAZE_REQUEST:
        return isSetBlaze_request();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof Process_args)
        return this.equals((Process_args)that);
      return false;
    }

    public boolean equals(Process_args that) {
      if (that == null)
        return false;

      boolean this_present_blaze_request = true && this.isSetBlaze_request();
      boolean that_present_blaze_request = true && that.isSetBlaze_request();
      if (this_present_blaze_request || that_present_blaze_request) {
        if (!(this_present_blaze_request && that_present_blaze_request))
          return false;
        if (!this.blaze_request.equals(that.blaze_request))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_blaze_request = true && (isSetBlaze_request());
      list.add(present_blaze_request);
      if (present_blaze_request)
        list.add(blaze_request);

      return list.hashCode();
    }

    @Override
    public int compareTo(Process_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetBlaze_request()).compareTo(other.isSetBlaze_request());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetBlaze_request()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.blaze_request, other.blaze_request);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("Process_args(");
      boolean first = true;

      sb.append("blaze_request:");
      if (this.blaze_request == null) {
        sb.append("null");
      } else {
        sb.append(this.blaze_request);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (blaze_request != null) {
        blaze_request.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class Process_argsStandardSchemeFactory implements SchemeFactory {
      public Process_argsStandardScheme getScheme() {
        return new Process_argsStandardScheme();
      }
    }

    private static class Process_argsStandardScheme extends StandardScheme<Process_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, Process_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // BLAZE_REQUEST
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.blaze_request = new BlazeRequestWrapper();
                struct.blaze_request.read(iprot);
                struct.setBlaze_requestIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, Process_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.blaze_request != null) {
          oprot.writeFieldBegin(BLAZE_REQUEST_FIELD_DESC);
          struct.blaze_request.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class Process_argsTupleSchemeFactory implements SchemeFactory {
      public Process_argsTupleScheme getScheme() {
        return new Process_argsTupleScheme();
      }
    }

    private static class Process_argsTupleScheme extends TupleScheme<Process_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, Process_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetBlaze_request()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetBlaze_request()) {
          struct.blaze_request.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, Process_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.blaze_request = new BlazeRequestWrapper();
          struct.blaze_request.read(iprot);
          struct.setBlaze_requestIsSet(true);
        }
      }
    }

  }

  public static class Process_result implements org.apache.thrift.TBase<Process_result, Process_result._Fields>, java.io.Serializable, Cloneable, Comparable<Process_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Process_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);
    private static final org.apache.thrift.protocol.TField OPERATION_FAILURE_FIELD_DESC = new org.apache.thrift.protocol.TField("operation_failure", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new Process_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new Process_resultTupleSchemeFactory());
    }

    public BlazeResponseWrapper success; // required
    public OperationFailure operation_failure; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      OPERATION_FAILURE((short)1, "operation_failure");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // OPERATION_FAILURE
            return OPERATION_FAILURE;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BlazeResponseWrapper.class)));
      tmpMap.put(_Fields.OPERATION_FAILURE, new org.apache.thrift.meta_data.FieldMetaData("operation_failure", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Process_result.class, metaDataMap);
    }

    public Process_result() {
    }

    public Process_result(
      BlazeResponseWrapper success,
      OperationFailure operation_failure)
    {
      this();
      this.success = success;
      this.operation_failure = operation_failure;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public Process_result(Process_result other) {
      if (other.isSetSuccess()) {
        this.success = new BlazeResponseWrapper(other.success);
      }
      if (other.isSetOperation_failure()) {
        this.operation_failure = new OperationFailure(other.operation_failure);
      }
    }

    public Process_result deepCopy() {
      return new Process_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
      this.operation_failure = null;
    }

    public BlazeResponseWrapper getSuccess() {
      return this.success;
    }

    public Process_result setSuccess(BlazeResponseWrapper success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public OperationFailure getOperation_failure() {
      return this.operation_failure;
    }

    public Process_result setOperation_failure(OperationFailure operation_failure) {
      this.operation_failure = operation_failure;
      return this;
    }

    public void unsetOperation_failure() {
      this.operation_failure = null;
    }

    /** Returns true if field operation_failure is set (has been assigned a value) and false otherwise */
    public boolean isSetOperation_failure() {
      return this.operation_failure != null;
    }

    public void setOperation_failureIsSet(boolean value) {
      if (!value) {
        this.operation_failure = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((BlazeResponseWrapper)value);
        }
        break;

      case OPERATION_FAILURE:
        if (value == null) {
          unsetOperation_failure();
        } else {
          setOperation_failure((OperationFailure)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case OPERATION_FAILURE:
        return getOperation_failure();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case OPERATION_FAILURE:
        return isSetOperation_failure();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof Process_result)
        return this.equals((Process_result)that);
      return false;
    }

    public boolean equals(Process_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_operation_failure = true && this.isSetOperation_failure();
      boolean that_present_operation_failure = true && that.isSetOperation_failure();
      if (this_present_operation_failure || that_present_operation_failure) {
        if (!(this_present_operation_failure && that_present_operation_failure))
          return false;
        if (!this.operation_failure.equals(that.operation_failure))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      boolean present_operation_failure = true && (isSetOperation_failure());
      list.add(present_operation_failure);
      if (present_operation_failure)
        list.add(operation_failure);

      return list.hashCode();
    }

    @Override
    public int compareTo(Process_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetOperation_failure()).compareTo(other.isSetOperation_failure());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetOperation_failure()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operation_failure, other.operation_failure);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("Process_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("operation_failure:");
      if (this.operation_failure == null) {
        sb.append("null");
      } else {
        sb.append(this.operation_failure);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class Process_resultStandardSchemeFactory implements SchemeFactory {
      public Process_resultStandardScheme getScheme() {
        return new Process_resultStandardScheme();
      }
    }

    private static class Process_resultStandardScheme extends StandardScheme<Process_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, Process_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new BlazeResponseWrapper();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // OPERATION_FAILURE
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.operation_failure = new OperationFailure();
                struct.operation_failure.read(iprot);
                struct.setOperation_failureIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, Process_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.operation_failure != null) {
          oprot.writeFieldBegin(OPERATION_FAILURE_FIELD_DESC);
          struct.operation_failure.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class Process_resultTupleSchemeFactory implements SchemeFactory {
      public Process_resultTupleScheme getScheme() {
        return new Process_resultTupleScheme();
      }
    }

    private static class Process_resultTupleScheme extends TupleScheme<Process_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, Process_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetOperation_failure()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
        if (struct.isSetOperation_failure()) {
          struct.operation_failure.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, Process_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.success = new BlazeResponseWrapper();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.operation_failure = new OperationFailure();
          struct.operation_failure.read(iprot);
          struct.setOperation_failureIsSet(true);
        }
      }
    }

  }

}
