/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thilenius.blaze.proto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-20")
public class MinecraftAccount implements org.apache.thrift.TBase<MinecraftAccount, MinecraftAccount._Fields>, java.io.Serializable, Cloneable, Comparable<MinecraftAccount> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MinecraftAccount");

  private static final org.apache.thrift.protocol.TField USER_UUID_FIELD_DESC = new org.apache.thrift.protocol.TField("user_uuid", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField MINECRAFT_USERNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("minecraft_username", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MinecraftAccountStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MinecraftAccountTupleSchemeFactory());
  }

  public String user_uuid; // required
  public String minecraft_username; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_UUID((short)1, "user_uuid"),
    MINECRAFT_USERNAME((short)2, "minecraft_username");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_UUID
          return USER_UUID;
        case 2: // MINECRAFT_USERNAME
          return MINECRAFT_USERNAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_UUID, new org.apache.thrift.meta_data.FieldMetaData("user_uuid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MINECRAFT_USERNAME, new org.apache.thrift.meta_data.FieldMetaData("minecraft_username", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MinecraftAccount.class, metaDataMap);
  }

  public MinecraftAccount() {
  }

  public MinecraftAccount(
    String user_uuid,
    String minecraft_username)
  {
    this();
    this.user_uuid = user_uuid;
    this.minecraft_username = minecraft_username;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MinecraftAccount(MinecraftAccount other) {
    if (other.isSetUser_uuid()) {
      this.user_uuid = other.user_uuid;
    }
    if (other.isSetMinecraft_username()) {
      this.minecraft_username = other.minecraft_username;
    }
  }

  public MinecraftAccount deepCopy() {
    return new MinecraftAccount(this);
  }

  @Override
  public void clear() {
    this.user_uuid = null;
    this.minecraft_username = null;
  }

  public String getUser_uuid() {
    return this.user_uuid;
  }

  public MinecraftAccount setUser_uuid(String user_uuid) {
    this.user_uuid = user_uuid;
    return this;
  }

  public void unsetUser_uuid() {
    this.user_uuid = null;
  }

  /** Returns true if field user_uuid is set (has been assigned a value) and false otherwise */
  public boolean isSetUser_uuid() {
    return this.user_uuid != null;
  }

  public void setUser_uuidIsSet(boolean value) {
    if (!value) {
      this.user_uuid = null;
    }
  }

  public String getMinecraft_username() {
    return this.minecraft_username;
  }

  public MinecraftAccount setMinecraft_username(String minecraft_username) {
    this.minecraft_username = minecraft_username;
    return this;
  }

  public void unsetMinecraft_username() {
    this.minecraft_username = null;
  }

  /** Returns true if field minecraft_username is set (has been assigned a value) and false otherwise */
  public boolean isSetMinecraft_username() {
    return this.minecraft_username != null;
  }

  public void setMinecraft_usernameIsSet(boolean value) {
    if (!value) {
      this.minecraft_username = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_UUID:
      if (value == null) {
        unsetUser_uuid();
      } else {
        setUser_uuid((String)value);
      }
      break;

    case MINECRAFT_USERNAME:
      if (value == null) {
        unsetMinecraft_username();
      } else {
        setMinecraft_username((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_UUID:
      return getUser_uuid();

    case MINECRAFT_USERNAME:
      return getMinecraft_username();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_UUID:
      return isSetUser_uuid();
    case MINECRAFT_USERNAME:
      return isSetMinecraft_username();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MinecraftAccount)
      return this.equals((MinecraftAccount)that);
    return false;
  }

  public boolean equals(MinecraftAccount that) {
    if (that == null)
      return false;

    boolean this_present_user_uuid = true && this.isSetUser_uuid();
    boolean that_present_user_uuid = true && that.isSetUser_uuid();
    if (this_present_user_uuid || that_present_user_uuid) {
      if (!(this_present_user_uuid && that_present_user_uuid))
        return false;
      if (!this.user_uuid.equals(that.user_uuid))
        return false;
    }

    boolean this_present_minecraft_username = true && this.isSetMinecraft_username();
    boolean that_present_minecraft_username = true && that.isSetMinecraft_username();
    if (this_present_minecraft_username || that_present_minecraft_username) {
      if (!(this_present_minecraft_username && that_present_minecraft_username))
        return false;
      if (!this.minecraft_username.equals(that.minecraft_username))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_user_uuid = true && (isSetUser_uuid());
    list.add(present_user_uuid);
    if (present_user_uuid)
      list.add(user_uuid);

    boolean present_minecraft_username = true && (isSetMinecraft_username());
    list.add(present_minecraft_username);
    if (present_minecraft_username)
      list.add(minecraft_username);

    return list.hashCode();
  }

  @Override
  public int compareTo(MinecraftAccount other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUser_uuid()).compareTo(other.isSetUser_uuid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUser_uuid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.user_uuid, other.user_uuid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMinecraft_username()).compareTo(other.isSetMinecraft_username());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinecraft_username()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.minecraft_username, other.minecraft_username);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MinecraftAccount(");
    boolean first = true;

    sb.append("user_uuid:");
    if (this.user_uuid == null) {
      sb.append("null");
    } else {
      sb.append(this.user_uuid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("minecraft_username:");
    if (this.minecraft_username == null) {
      sb.append("null");
    } else {
      sb.append(this.minecraft_username);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MinecraftAccountStandardSchemeFactory implements SchemeFactory {
    public MinecraftAccountStandardScheme getScheme() {
      return new MinecraftAccountStandardScheme();
    }
  }

  private static class MinecraftAccountStandardScheme extends StandardScheme<MinecraftAccount> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MinecraftAccount struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_UUID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.user_uuid = iprot.readString();
              struct.setUser_uuidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MINECRAFT_USERNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.minecraft_username = iprot.readString();
              struct.setMinecraft_usernameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MinecraftAccount struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.user_uuid != null) {
        oprot.writeFieldBegin(USER_UUID_FIELD_DESC);
        oprot.writeString(struct.user_uuid);
        oprot.writeFieldEnd();
      }
      if (struct.minecraft_username != null) {
        oprot.writeFieldBegin(MINECRAFT_USERNAME_FIELD_DESC);
        oprot.writeString(struct.minecraft_username);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MinecraftAccountTupleSchemeFactory implements SchemeFactory {
    public MinecraftAccountTupleScheme getScheme() {
      return new MinecraftAccountTupleScheme();
    }
  }

  private static class MinecraftAccountTupleScheme extends TupleScheme<MinecraftAccount> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MinecraftAccount struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetUser_uuid()) {
        optionals.set(0);
      }
      if (struct.isSetMinecraft_username()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetUser_uuid()) {
        oprot.writeString(struct.user_uuid);
      }
      if (struct.isSetMinecraft_username()) {
        oprot.writeString(struct.minecraft_username);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MinecraftAccount struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.user_uuid = iprot.readString();
        struct.setUser_uuidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.minecraft_username = iprot.readString();
        struct.setMinecraft_usernameIsSet(true);
      }
    }
  }

}

