#!/bin/bash
. $HOME/thilenius/core/shell/base
set -e

INFO 'Compiling Blaze service files'
#rm -rf /root/thilenius_bin/scorch/anvil/python/package
mkdir --parents /root/thilenius_bin/scorch/anvil/python/package/scorch
thrift -r --gen py -I /root/thilenius \
    -out /root/thilenius_bin/scorch/anvil/python/package \
    /root/thilenius/scorch/cloud/blaze/blaze.thrift || \
    EROR 'Failed to build Blaze service files'

INFO 'Copying asset files'
cp -r /root/thilenius/scorch/anvil/python/* \
    /root/thilenius_bin/scorch/anvil/python/package/scorch

INFO 'Installing Anvil python build'
mkdir --parent /usr/local/lib/python2.7/dist-packages/anvil
cp -r /root/thilenius_bin/scorch/anvil/python/package/* \
    /usr/local/lib/python2.7/dist-packages
