#!/bin/bash
. $HOME/thilenius/core/shell/base
set -e

wget https://pypi.python.org/packages/source/t/thrift/thrift-0.9.2.tar.gz
tar -xvf thrift-0.9.2.tar.gz
pushd thrift-0.9.2
python setup.py install
popd
rm -rf thrift-0.9.2* thrift.egg-info
