#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

SECONDARY_THRESHOLD = 0
USER_THRESHOLD = 20
MODERATOR_THRESHOLD = 40
ADMIN_THRESHOLD = 60
SUPER_THRESHOLD = 80
