. $HOME/thilenius/core/shell/*
PATH=$PATH:$HOME/thilenius/core/tools

export CC=/usr/bin/clang-3.6
export CXX=/usr/bin/clang++-3.6

#===  MISX ALIASES  ============================================================
alias rgrep='GREP_COLOR="1;37;41" LANG=C grep -r --color=auto'
alias thilenius='cd $HOME/thilenius'
LS_COLORS=$LS_COLORS:'di=0;35:' ; export LS_COLORS
