PATH=$PATH:$HOME/thilenius/core/shell

#===  MISX ALIASES  ============================================================
alias rgrep='GREP_COLOR="1;37;41" LANG=C grep -r --color=auto'
alias thilenius='cd $HOME/thilenius'
