#===============================================================================
#===  DEV_ENV  =================================================================
#===============================================================================
FROM athilenius/base

#===  UPDATE apt-get  ==========================================================
RUN apt-get update -q

#===  MISX APT-GET  ============================================================
RUN apt-get install -y \
  autoconf \
  bison \
  cmake \
  default-jdk \
  exuberant-ctags \
  flex \
  g++ \
  git \
  libboost-all-dev \
  libdouble-conversion-dev \
  libevent-dev \
  libgoogle-glog-dev \
  libkrb5-dev \
  libnuma-dev \
  libsasl2-dev \
  libsnappy-dev \
  libssl-dev \
  libtool \
  make \
  nginx \
  scons \
  tmux \
  unzip \
  wget \
  zip

#===  PYTHON 2.7  ==============================================================
RUN apt-get install -y python python-pip python-dev pylint
RUN pip install yapf

#===  NODEJS / NPM  ============================================================
RUN curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
RUN apt-get install -y nodejs

#===  CLANG  ===================================================================
RUN apt-get install -y build-essential
RUN apt-get install -y libc++-dev libc++abi-dev clang-3.6 lldb-3.6
RUN ln -s /usr/bin/clang-3.6 /usr/bin/clang
RUN ln -s /usr/bin/clang++-3.6 /usr/bin/clang++

#===  FORMATTERS  ==============================================================
RUN npm install -g jscs jscs-angular
RUN apt-get install -y clang-format-3.6
RUN ln /usr/bin/clang-format-3.6 /usr/bin/clang-format

#===  VIM PLUGINS  =============================================================
ADD vimrc_plugins /root/env_files/
RUN mv /root/env_files/vimrc_plugins /root/.vimrc
RUN apt-get install -qy vim
RUN git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
RUN vim +PluginInstall +qall

#===  TERN FOR VIM  ============================================================
RUN cd /root/.vim/bundle/tern_for_vim && npm install

#===  YOU COMPLETE ME  =========================================================
RUN export CC=/usr/bin/clang-3.6 && \
    export CXX=/usr/bin/clang++-3.6 && \
    export CXXFLAGS=--std=c++11 && \
    cd /root/.vim/bundle/YouCompleteMe && \
    ./install.py --clang-completer --system-libclang

#===  MONO  ====================================================================
#RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
#RUN echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
#RUN apt-get update -y
#RUN apt-get install -y mono-devel

#===  SCALA / SBT / JAVA  ======================================================
#RUN wget www.scala-lang.org/files/archive/scala-2.11.7.deb
#RUN dpkg -i scala-2.11.7.deb

#RUN echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
#RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
#RUN apt-get update
#RUN apt-get install -y sbt

#===  NPM packages =============================================================
RUN npm install -g strongloop bower grunt-cli --unsafe-perm

#===  VIM RC  ==================================================================
ADD vimrc /root/env_files/
RUN cat /root/env_files/vimrc >> /root/.vimrc
RUN mkdir --parent /root/.vim/swapfiles
RUN mkdir --parent /root/.vim/bakfiles

#===  MISX FILES  ==============================================================
ADD bashrc /root/env_files/
RUN mv /root/env_files/bashrc /root/.bashrc

ADD jscsrc /root/env_files/
RUN mv /root/env_files/jscsrc /root/.jscsrc

ADD clang-format /root/env_files/
RUN mv /root/env_files/clang-format /root/.clang-format

#===  CMD  =====================================================================
CMD /bin/bash
