#!/bin/bash
. $HOME/thilenius/core/shell/base

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

mkdir --parent /root/thilenius/open_to_lan/client/gen-files

INFO 'Compiling lb Services'
lb-ng /root/thilenius/open_to_lan/server/server.js \
    /root/thilenius/open_to_lan/client/gen-files/lb_services.js || \
    EROR 'Failed to build lb service files'

TIMESTAMP=$(date +%y%m%d.%H.%M%S)

function GlobJsToIndex {
  find $1 -name *.js | while read line; do \
    echo "<script src=\"$line\"></script>" >> index.html; \
  done
}

function GlobCssToIndex {
  find $1 -name *.css | while read line; do \
    echo "<link rel=\"stylesheet\" href=\"$line\" />" >> index.html; \
  done
}

INFO 'Createing a development index.html file'
pushd /root/thilenius/open_to_lan/client
rm -rf /root/thilenius/open_to_lan/client/index.html
cat << EOM >> index.html
<!doctype html>
<html ng-app="app" ng-controller="loginController"
      class="{{\$root.htmlClass ? \$root.htmlClass : 'default-body'}}">
<head><title ng-bind="\$root.title || 'Open To Lan'"></title>
<link rel="shortcut icon" href="assets/flame-512.png" />
<link href="vendor/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
<link href="vendor/angular-xeditable/dist/css/xeditable.css" rel="stylesheet">
<script src="vendor/jquery/dist/jquery.js"></script>
<script src="vendor/bootstrap/dist/js/bootstrap.js"></script>
<script src="vendor/angular/angular.js"></script>
<script src="vendor/angular-resource/angular-resource.js"></script>
<script src="vendor/angular-ui-router/release/angular-ui-router.js"></script>
<script src="vendor/angular-cookies/angular-cookies.js"></script>
<script src="vendor/angular-xeditable/dist/js/xeditable.js"></script>
<script src="vendor/underscore/underscore-min.js"></script>
EOM
echo "<script>var OTL_VERSION=\"${TIMESTAMP}\";</script>" >> index.html

# Bower
#pushd /root/thilenius/open_to_lan
#bower --allow-root install \
  #angular \
  #angular-cookies \
  #angular-resource \
  #angular-ui-router \
  #angular-xeditable \
  #bootstrap \
  #underscore
#popd

GlobCssToIndex libs_precomp
GlobJsToIndex libs_precomp

GlobCssToIndex libs
GlobJsToIndex libs

GlobCssToIndex assets
GlobJsToIndex assets

GlobCssToIndex gen-files
GlobJsToIndex gen-files

GlobCssToIndex app
GlobJsToIndex app

cat << EOM >> index.html
</head>
<body class="{{\$root.bodyClass ? \$root.bodyClass : 'default-body'}}">
<div ui-view></div>
</body></html>
EOM
popd

