#!/bin/bash
. $HOME/thilenius/core/shell/base

DEFINE_string mount_point "$HOME/data/nginx/static"\
    'The data mount point for static assets the nginx will serve' m

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

INFO 'Killing any old Docker Containers'
docker kill nginx_dev 2> /dev/null
docker rm nginx_dev 2> /dev/null

INFO 'Building Docker image'
docker build -t athilenius/nginx:dev $HOME/thilenius/cloud/nginx/dev ||\
    EROR 'Failed to build Dockerfile'

INFO "Making sure ${FLAGS_mount_point} exsits"
mkdir -p ${FLAGS_mount_point} ||\
    EROR "Failed to make ${FLAGS_mount_point} directory"

INFO 'Starting Docker container'
docker run -d -p 80:80 -v ${FLAGS_mount_point}:/data/nginx/static\
    --name nginx_dev --env-file=/etc/environment athilenius/nginx:dev

CONTAINER_ID=$(docker ps -a | grep athilenius/nginx:dev | cut -f1 -d" ")
INFO "Started in container [$CONTAINER_ID]. Waiting a few seconds for logs"
sleep 4
docker logs $CONTAINER_ID
