#!/bin/bash
. $HOME/thilenius/core/shell/base

DEFINE_string mount_point "/data/nginx/static" \
    'The data mount point for static assets the nginx will serve' m

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

INFO 'Compiling Sentinel service files'
mkdir --parent /root/thilenius_gen/scorch/forge
thrift -r --gen js:jquery -I /root/thilenius \
    -out /root/thilenius_gen/scorch/forge \
    /root/thilenius/cloud/sentinel/sentinel.thrift || \
    EROR 'Failed to build Sentinel service files'

INFO 'Compiling Crucible service files'
mkdir --parent /root/thilenius_gen/scorch/forge
thrift -r --gen js:jquery -I /root/thilenius \
    -out /root/thilenius_gen/scorch/forge \
    /root/thilenius/scorch/cloud/crucible/crucible.thrift || \
    EROR 'Failed to build Crucible service files'

INFO 'Compiling Billet service files'
mkdir --parent /root/thilenius_gen/scorch/forge
thrift -r --gen js:jquery -I /root/thilenius \
    -out /root/thilenius_gen/scorch/forge \
    /root/thilenius/scorch/cloud/billet/billet.thrift || \
    EROR 'Failed to build Billet service files'

INFO "Making sure ${FLAGS_mount_point} exsits"
mkdir -p ${FLAGS_mount_point} || \
    EROR "Failed to make ${FLAGS_mount_point} directory"

INFO "Clearing ${FLAGS_mount_point}"
rm -rf ${FLAGS_mount_point}/* || EROR "Failed to clear ${FLAGS_mount_point}"

INFO "Copying gen_files to ${FLAGS_mount_point}/gen_files"
cp -r $HOME/thilenius_gen/scorch/forge ${FLAGS_mount_point}/gen_files || \
    EROR "Failed to copy gen_files to ${FLAGS_mount_point}/gen_files"

INFO "Copying thrift.min.js to ${FLAGS_mount_point}/gen_files"
cp /root/thilenius/scorch/forge/thrift.min.js \
    ${FLAGS_mount_point}/gen_files/thrift.js || \
    EROR "Failed to copy thrift.min.js to ${FLAGS_output}/thrift.js"

INFO "Copying src to ${FLAGS_mount_point}/"
cp -r $HOME/thilenius/scorch/forge/src/* ${FLAGS_mount_point}

INFO 'Changing owner to www-data'
sudo chown -R www-data /data

INFO 'Reloading nginx'
nginx -s reopen
nginx -s reload
