#!/bin/bash
. $HOME/thilenius/core/shell/base

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

mkdir --parent /root/thilenius/scorch/forge/gen-files

INFO 'Compiling Sentinel service files'
thrift -r --gen js:jquery -I /root/thilenius \
    -out /root/thilenius/scorch/forge/gen-files \
    /root/thilenius/cloud/sentinel/sentinel.thrift || \
    EROR 'Failed to build Sentinel service files'

INFO 'Compiling Crucible service files'
thrift -r --gen js:jquery -I /root/thilenius \
    -out /root/thilenius/scorch/forge/gen-files \
    /root/thilenius/scorch/cloud/crucible/crucible.thrift || \
    EROR 'Failed to build Crucible service files'

INFO 'Compiling Billet service files'
thrift -r --gen js:jquery -I /root/thilenius \
    -out /root/thilenius/scorch/forge/gen-files \
    /root/thilenius/scorch/cloud/billet/billet.thrift || \
    EROR 'Failed to build Billet service files'

INFO 'Compiling Blaze service files'
thrift -r --gen js:jquery -I /root/thilenius \
    -out /root/thilenius/scorch/forge/gen-files \
    /root/thilenius/scorch/cloud/blaze/blaze.thrift || \
    EROR 'Failed to build Blaze service files'

INFO 'Compiling Fiber service files'
thrift -r --gen js:jquery -I /root/thilenius \
    -out /root/thilenius/scorch/forge/gen-files \
    /root/thilenius/cloud/fiber/fiber.thrift || \
    EROR 'Failed to build Fiber service files'

TIMESTAMP=$(date +%y%m%d.%H.%M%S)

function GlobJsToIndex {
  find $1 -name *.js | while read line; do \
    echo "<script src=\"$line\"></script>" >> index.html; \
  done
}

function GlobCssToIndex {
  find $1 -name *.css | while read line; do \
    echo "<link rel=\"stylesheet\" href=\"$line\" />" >> index.html; \
  done
}

INFO 'Createing a development index.html file'
pushd /root/thilenius/scorch/forge
rm -rf /root/thilenius/scorch/forge/index.html
cat << EOM >> index.html
<!doctype html>
<html ng-app="forgeApp" ng-controller="loginController"
      class="{{\$root.htmlClass ? \$root.htmlClass : 'forge-body'}}">
<head><title ng-bind="\$root.title || 'Forge'"></title>
<link rel="shortcut icon" href="assets/flame-512.png" />
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" />
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular-route.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular-cookies.js"></script>
<script src="https://cdn.jsdelivr.net/ace/1.2.0/min/ace.js"></script>
<script src="https://cdn.jsdelivr.net/ace/1.2.0/min/ext-language_tools.js"></script>
EOM
echo "<script>var FORGE_VERSION=\"${TIMESTAMP}\";</script>" >> index.html

GlobCssToIndex libs
GlobJsToIndex libs

GlobCssToIndex assets
GlobJsToIndex assets

GlobCssToIndex gen-files
GlobJsToIndex gen-files

GlobCssToIndex app
GlobJsToIndex app

cat << EOM >> index.html
</head>
<body ng-view class="{{\$root.bodyClass ? \$root.bodyClass : 'forge-body'}}">
</body></html>
EOM
popd

INFO 'Updating NGINX'
rm -rf /etc/nginx/sites-available/*
cp /root/thilenius/scorch/forge/nginx_dev /etc/nginx/sites-available/default
cp /root/thilenius/scorch/forge/nginx.conf /etc/nginx/nginx.conf
nginx -s reload
