#!/bin/bash
. $HOME/thilenius/core/shell/base

DEFINE_string mount_point "$HOME/data/mongodb"\
    'The data mount point for the mongodb instance' m

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

INFO 'Killing any old Docker Containers'
docker kill mongo_dev 2> /dev/null
docker rm mongo_dev 2> /dev/null

INFO 'Building Docker image'
docker build -t athilenius/mongo:dev $HOME/thilenius/cloud/mongo_db ||\
    EROR 'Failed to build Docker Image'

INFO "Making sure ${FLAGS_mount_point} exsits"
mkdir -p ${FLAGS_mount_point} ||\
    EROR "Failed to make ${FLAGS_mount_point} directory"

# Always use default MongoDB port (to prevent orphaned services)
PORT=27017
INFO "Starting Docker container on port $PORT"
CONTAINER_ID=$(docker run -d -p $PORT:27017\
    --name mongo_dev -e DOCKER_PORT=$PORT\
    athilenius/mongo:dev)
# Removed because I can't mound an OSX file for mongo
# -v ${FLAGS_mount_point}:/data/mongodb

INFO "Started in container [$CONTAINER_ID]. Waiting a few seconds for logs"
sleep 4
docker logs $CONTAINER_ID
