#!/bin/bash
. $HOME/thilenius/core/shell/base
set -e

if [ "${USER}" = "Alec"  ]; then
  docker build -t athilenius/billet_client:prod .
  docker push athilenius/billet_client:prod
else
  INFO 'Building Anvil Python'
  pushd /root/thilenius/scorch/anvil/python
  ./build_py
  popd
  INFO 'Packaging Anvil Python'
  mkdir --parent /root/thilenius/scorch/cloud/billet/packages/anvil/python
  cp -r /root/thilenius_bin/scorch/anvil/python/package/* \
      /root/thilenius/scorch/cloud/billet/packages/anvil/python
fi
