/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thilenius.sentinel.proto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-20")
public class Token implements org.apache.thrift.TBase<Token, Token._Fields>, java.io.Serializable, Cloneable, Comparable<Token> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Token");

  private static final org.apache.thrift.protocol.TField USER_UUID_FIELD_DESC = new org.apache.thrift.protocol.TField("user_uuid", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TOKEN_UUID_FIELD_DESC = new org.apache.thrift.protocol.TField("token_uuid", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PERMISSION_LEVEL_FIELD_DESC = new org.apache.thrift.protocol.TField("permission_level", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TokenStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TokenTupleSchemeFactory());
  }

  public String user_uuid; // required
  public String token_uuid; // required
  public int permission_level; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_UUID((short)1, "user_uuid"),
    TOKEN_UUID((short)2, "token_uuid"),
    PERMISSION_LEVEL((short)3, "permission_level");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_UUID
          return USER_UUID;
        case 2: // TOKEN_UUID
          return TOKEN_UUID;
        case 3: // PERMISSION_LEVEL
          return PERMISSION_LEVEL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PERMISSION_LEVEL_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_UUID, new org.apache.thrift.meta_data.FieldMetaData("user_uuid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TOKEN_UUID, new org.apache.thrift.meta_data.FieldMetaData("token_uuid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PERMISSION_LEVEL, new org.apache.thrift.meta_data.FieldMetaData("permission_level", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Token.class, metaDataMap);
  }

  public Token() {
  }

  public Token(
    String user_uuid,
    String token_uuid,
    int permission_level)
  {
    this();
    this.user_uuid = user_uuid;
    this.token_uuid = token_uuid;
    this.permission_level = permission_level;
    setPermission_levelIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Token(Token other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetUser_uuid()) {
      this.user_uuid = other.user_uuid;
    }
    if (other.isSetToken_uuid()) {
      this.token_uuid = other.token_uuid;
    }
    this.permission_level = other.permission_level;
  }

  public Token deepCopy() {
    return new Token(this);
  }

  @Override
  public void clear() {
    this.user_uuid = null;
    this.token_uuid = null;
    setPermission_levelIsSet(false);
    this.permission_level = 0;
  }

  public String getUser_uuid() {
    return this.user_uuid;
  }

  public Token setUser_uuid(String user_uuid) {
    this.user_uuid = user_uuid;
    return this;
  }

  public void unsetUser_uuid() {
    this.user_uuid = null;
  }

  /** Returns true if field user_uuid is set (has been assigned a value) and false otherwise */
  public boolean isSetUser_uuid() {
    return this.user_uuid != null;
  }

  public void setUser_uuidIsSet(boolean value) {
    if (!value) {
      this.user_uuid = null;
    }
  }

  public String getToken_uuid() {
    return this.token_uuid;
  }

  public Token setToken_uuid(String token_uuid) {
    this.token_uuid = token_uuid;
    return this;
  }

  public void unsetToken_uuid() {
    this.token_uuid = null;
  }

  /** Returns true if field token_uuid is set (has been assigned a value) and false otherwise */
  public boolean isSetToken_uuid() {
    return this.token_uuid != null;
  }

  public void setToken_uuidIsSet(boolean value) {
    if (!value) {
      this.token_uuid = null;
    }
  }

  public int getPermission_level() {
    return this.permission_level;
  }

  public Token setPermission_level(int permission_level) {
    this.permission_level = permission_level;
    setPermission_levelIsSet(true);
    return this;
  }

  public void unsetPermission_level() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PERMISSION_LEVEL_ISSET_ID);
  }

  /** Returns true if field permission_level is set (has been assigned a value) and false otherwise */
  public boolean isSetPermission_level() {
    return EncodingUtils.testBit(__isset_bitfield, __PERMISSION_LEVEL_ISSET_ID);
  }

  public void setPermission_levelIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PERMISSION_LEVEL_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_UUID:
      if (value == null) {
        unsetUser_uuid();
      } else {
        setUser_uuid((String)value);
      }
      break;

    case TOKEN_UUID:
      if (value == null) {
        unsetToken_uuid();
      } else {
        setToken_uuid((String)value);
      }
      break;

    case PERMISSION_LEVEL:
      if (value == null) {
        unsetPermission_level();
      } else {
        setPermission_level((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_UUID:
      return getUser_uuid();

    case TOKEN_UUID:
      return getToken_uuid();

    case PERMISSION_LEVEL:
      return Integer.valueOf(getPermission_level());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_UUID:
      return isSetUser_uuid();
    case TOKEN_UUID:
      return isSetToken_uuid();
    case PERMISSION_LEVEL:
      return isSetPermission_level();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Token)
      return this.equals((Token)that);
    return false;
  }

  public boolean equals(Token that) {
    if (that == null)
      return false;

    boolean this_present_user_uuid = true && this.isSetUser_uuid();
    boolean that_present_user_uuid = true && that.isSetUser_uuid();
    if (this_present_user_uuid || that_present_user_uuid) {
      if (!(this_present_user_uuid && that_present_user_uuid))
        return false;
      if (!this.user_uuid.equals(that.user_uuid))
        return false;
    }

    boolean this_present_token_uuid = true && this.isSetToken_uuid();
    boolean that_present_token_uuid = true && that.isSetToken_uuid();
    if (this_present_token_uuid || that_present_token_uuid) {
      if (!(this_present_token_uuid && that_present_token_uuid))
        return false;
      if (!this.token_uuid.equals(that.token_uuid))
        return false;
    }

    boolean this_present_permission_level = true;
    boolean that_present_permission_level = true;
    if (this_present_permission_level || that_present_permission_level) {
      if (!(this_present_permission_level && that_present_permission_level))
        return false;
      if (this.permission_level != that.permission_level)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_user_uuid = true && (isSetUser_uuid());
    list.add(present_user_uuid);
    if (present_user_uuid)
      list.add(user_uuid);

    boolean present_token_uuid = true && (isSetToken_uuid());
    list.add(present_token_uuid);
    if (present_token_uuid)
      list.add(token_uuid);

    boolean present_permission_level = true;
    list.add(present_permission_level);
    if (present_permission_level)
      list.add(permission_level);

    return list.hashCode();
  }

  @Override
  public int compareTo(Token other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUser_uuid()).compareTo(other.isSetUser_uuid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUser_uuid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.user_uuid, other.user_uuid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetToken_uuid()).compareTo(other.isSetToken_uuid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetToken_uuid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.token_uuid, other.token_uuid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPermission_level()).compareTo(other.isSetPermission_level());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPermission_level()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.permission_level, other.permission_level);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Token(");
    boolean first = true;

    sb.append("user_uuid:");
    if (this.user_uuid == null) {
      sb.append("null");
    } else {
      sb.append(this.user_uuid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("token_uuid:");
    if (this.token_uuid == null) {
      sb.append("null");
    } else {
      sb.append(this.token_uuid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("permission_level:");
    sb.append(this.permission_level);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TokenStandardSchemeFactory implements SchemeFactory {
    public TokenStandardScheme getScheme() {
      return new TokenStandardScheme();
    }
  }

  private static class TokenStandardScheme extends StandardScheme<Token> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Token struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_UUID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.user_uuid = iprot.readString();
              struct.setUser_uuidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TOKEN_UUID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.token_uuid = iprot.readString();
              struct.setToken_uuidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PERMISSION_LEVEL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.permission_level = iprot.readI32();
              struct.setPermission_levelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Token struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.user_uuid != null) {
        oprot.writeFieldBegin(USER_UUID_FIELD_DESC);
        oprot.writeString(struct.user_uuid);
        oprot.writeFieldEnd();
      }
      if (struct.token_uuid != null) {
        oprot.writeFieldBegin(TOKEN_UUID_FIELD_DESC);
        oprot.writeString(struct.token_uuid);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PERMISSION_LEVEL_FIELD_DESC);
      oprot.writeI32(struct.permission_level);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TokenTupleSchemeFactory implements SchemeFactory {
    public TokenTupleScheme getScheme() {
      return new TokenTupleScheme();
    }
  }

  private static class TokenTupleScheme extends TupleScheme<Token> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Token struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetUser_uuid()) {
        optionals.set(0);
      }
      if (struct.isSetToken_uuid()) {
        optionals.set(1);
      }
      if (struct.isSetPermission_level()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetUser_uuid()) {
        oprot.writeString(struct.user_uuid);
      }
      if (struct.isSetToken_uuid()) {
        oprot.writeString(struct.token_uuid);
      }
      if (struct.isSetPermission_level()) {
        oprot.writeI32(struct.permission_level);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Token struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.user_uuid = iprot.readString();
        struct.setUser_uuidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.token_uuid = iprot.readString();
        struct.setToken_uuidIsSet(true);
      }
      if (incoming.get(2)) {
        struct.permission_level = iprot.readI32();
        struct.setPermission_levelIsSet(true);
      }
    }
  }

}

