#!/bin/bash
. $HOME/thilenius/core/shell/base
trap 'kill $(jobs -p)' EXIT
set -e

INFO 'Compling Sentinel'
cd /root/thilenius/cloud/sentinel/server
build

INFO 'Compling Fiber'
cd /root/thilenius/cloud/fiber/server
build

INFO 'Compling Crucible'
cd /root/thilenius/scorch/cloud/crucible/server
build

INFO 'Compling Billet'
cd /root/thilenius/scorch/cloud/billet/server
build

INFO 'Compling Blaze'
cd /root/thilenius/scorch/cloud/blaze
build

INFO 'Starting nginx stack'
nginx || INFO 'Ignoring error from nginx'
/root/thilenius/scorch/forge/update_deps

HOST_IP=$(/sbin/ip route|awk '/default/ { print $3  }')
INFO "Using ${HOST_IP} for MongoDB"

INFO 'Starting Sentinel'
/root/thilenius_bin/cloud/sentinel/server/server --mongo_ip $HOST_IP &

INFO 'Starting Fiber'
/root/thilenius_bin/cloud/fiber/server/server --mongo_ip $HOST_IP &

INFO 'Starting Crucible'
/root/thilenius_bin/scorch/cloud/crucible/server/server --mongo_ip $HOST_IP &

INFO 'Starting Billet'
/root/thilenius_bin/scorch/cloud/billet/server/server \
    --host_billet_mount_point /Users/Alec/billet &

INFO 'Starting Blaze'
/root/thilenius_bin/scorch/cloud/blaze/blaze \
    --flame_ip 192.168.59.103 --mongo_ip $HOST_IP &

INFO 'Sleeping. Forever... Sheee, go to sleep.'
while true; do
  sleep 1000000000
done
